package com.sample.rules
 
 import com.sample.vall.value;
import java.util.HashMap;  


rule "Addition"
no-loop
ruleflow-group "Addition"
when	
     v:value(v.a!= 0 || v.b !=0);
     map:HashMap();
then	
		v.result=v.a+v.b;
	//	HashMap map = new HashMap();
	//	map.put("re",1);
		System.out.println("sri");
end


rule "Subtraction"
no-loop
ruleflow-group "Subtraction"
when	
     v:value(v.result != 0);		
then	
					
		v.result=v.a-v.b;
		System.out.println("sri"+v.result);
end

rule "Exception"
no-loop
ruleflow-group "Exception"
when	
     v:value(v.result == 0);		
then	
		System.out.println("Exception in Addition");
end